### ISSUE TITLE
FYI pygolang

### ISSUE THREAD

**Issue by navytux** [naphta/py-defer#1]
FYI pygolang, besides working channels and goroutines, also provides defer and panic/recover:

https://pypi.org/project/pygolang/#defer-recover-panic

**Comment by naphta** [comment]
I was aware of this to be honest, I put this together partially as a thought exercise and also to just provide a single simple function.

**Comment by navytux** [comment]
ok, sorry for the noise.

**Comment by naphta** [comment]
@navytux no problem at all, I think plenty of other people who find this might have the same reflection.
